### ISSUE TITLE
fhs latest version is 3.0, released on june 3 2015 - wikipedia

### ISSUE THREAD

**Issue by m-gh** [jadijadi/linuxandlife#12]
سلام.
اخرین ورژن اف اچ اس به نظر ۲۰۱۵ بوده. تو کتاب نوشتید ۲۰۰۴.
لینک آدرس کتاب:
http://linuxbook.ir/chapters/directory_structure.html

**Comment by jadijadi** [comment]
ممنون اصلاحش کردم. زمانی که می نوشتیم اون بود ولی باید آپدیت می شد. تشکر.
