### ISSUE TITLE
Footer Github Link

### ISSUE THREAD

**Issue by Ali-Xoerex** [jadijadi/linuxandlife#13]
سلام جادی جان.

در رابطه با مشکل لینک گیت هاب کتاب ، به نظر می رسه که تو ریپوزیتوری کتاب مشکلی نیست بلکه هاستی که سایت 
روی اون پیاده سازی شده ، با ریپوزیتوری سینک نیست.

ممنون

**Comment by jadijadi** [comment]
خیلی هم خوب. مرسی از خبر
