### ISSUE TITLE
پیشنهاد اضافه‌کردن آموزش proxychains به بخش استفاده از پروکسی

### ISSUE THREAD

**Issue by taghizadeh1987** [jadijadi/linuxandlife#5]
به نظرم بد نباشه توضیحی در مورد proxychains هم در مطالب گنجانده بشه. آموزش کوتاهی در مورد برنامه‌ی proxychains آماده کردم که در صورت صلاحدید اضافه بشه

```
استفاده از برنامه‌ی proxychains
-proxychains چیست؟
proxychains ابزاری است که به شما اجازه میدهد برنامه‌ها را از طریق پروکسی HTTP یا SOCKS اجرا کنید. به عنوان مثال برنامه‌ی aria2 که یک نرم‌افزار مدیریت دانلود است از پروکسی نوع SOCKS پشتیبانی نمی‌کند. با استفاده از proxychains قادر هستید برنامه‌های مختلف را تحت پروکسی اجرا نمایید. proxychains بطور کلی قابلیت استفاده از پروکسی‌های زیر را دارد:
http, socks4, socks5

-نصب proxychains
جهت نصب توسط مدیر بسته‌ی apt کافی است دستور زیر را در ترمینال وارد نمایید:
sudo apt-get install proxychains

-تنظیمات proxychains
جهت استفاده از proxychains باید مشخصات آی‌پی و پورت پروکسی موردنظر را در فایل تنظیمات وارد کرد. برای ویرایش تنظبمات این برنامه دستور زیر را در ترمینال وارد کنید:
sudo nano /etc/proxychains.conf
(می‌توانید از ویرایشگر متن دیگری مثلاً از gedit به جای nano استفاده کنید.)
پس از اجرای این دستور فایل تنظیمات در ویرایشگر باز میشود. در این فایل توضیحاتی در مورد ساختار فایل تنظیمات مشاهده میکنید. در قسمت آخر فایل یعنی در بخش [ProxyList] خطوط زیر دیده میشود:
# add proxy here ...
# meanwile
# defaults set to "tor"
socks4  127.0.0.1 9050
همانطور که مشاهده میکنید برنامه بصورت پیشفرض برای استفاده از آی‌پی و پورت برنامه‌ی پروکسی tor تنظیم گردیده است. درصورت لزوم میتوانید آی‌پی و پورت دیگری در خط جدید اضافه نمایید (مثلاً: http 127.0.0.1 8080) و سایر آی‌پی و پورت‌ها را حذف یا کامنت کنید. (درصورتی که کاراکتر # در ابتدای هر خط قرار گیرد، خط مذکور توضیح (comment) تلقی میگردد).

-اجرای  proxychains
برای اجرای یک نرم‌افزار با استفاده از proxychains دستور زیر را در ترمینال وارد کنید:
proxychains <name_of_application>
مثلاً:
proxychains firefox  
```

**Comment by farooghkz** [comment]
@taghizadeh1987: Use Pull Request instead of Issue
از پول ریکوئست استفاده کنید.

**Comment by MohamadHosseinMohammadi** [comment]
## استفاده از برنامه‌ی proxychains
-proxychains چیست؟
proxychains ابزاری است که به شما اجازه میدهد برنامه‌ها را از طریق پروکسی HTTP یا SOCKS اجرا کنید. به عنوان مثال برنامه‌ی aria2 که یک نرم‌افزار مدیریت دانلود است از پروکسی نوع SOCKS پشتیبانی نمی‌کند. با استفاده از proxychains قادر هستید برنامه‌های مختلف را تحت پروکسی اجرا نمایید. proxychains بطور کلی قابلیت استفاده از پروکسی‌های زیر را دارد:
http, socks4, socks5

## -نصب proxychains
جهت نصب توسط مدیر بسته‌ی apt کافی است دستور زیر را در ترمینال وارد نمایید:
sudo apt-get install proxychains

## -تنظیمات proxychains
جهت استفاده از proxychains باید مشخصات آی‌پی و پورت پروکسی موردنظر را در فایل تنظیمات وارد کرد. برای ویرایش تنظبمات این برنامه دستور زیر را در ترمینال وارد کنید:
sudo nano /etc/proxychains.conf
(می‌توانید از ویرایشگر متن دیگری مثلاً از gedit به جای nano استفاده کنید.)
پس از اجرای این دستور فایل تنظیمات در ویرایشگر باز میشود. در این فایل توضیحاتی در مورد ساختار فایل تنظیمات مشاهده میکنید. در قسمت آخر فایل یعنی در بخش [ProxyList] خطوط زیر دیده میشود:
# add proxy here ...
# meanwile
# defaults set to "tor"
socks4  127.0.0.1 9050
همانطور که مشاهده میکنید برنامه بصورت پیشفرض برای استفاده از آی‌پی و پورت برنامه‌ی پروکسی tor تنظیم گردیده است. درصورت لزوم میتوانید آی‌پی و پورت دیگری در خط جدید اضافه نمایید (مثلاً: http 127.0.0.1 8080) و سایر آی‌پی و پورت‌ها را حذف یا کامنت کنید. (درصورتی که کاراکتر # در ابتدای هر خط قرار گیرد، خط مذکور توضیح (comment) تلقی میگردد).

## -اجرای  proxychains
برای اجرای یک نرم‌افزار با استفاده از proxychains دستور زیر را در ترمینال وارد کنید:
proxychains <name_of_application>
مثلاً:
proxychains firefox

**Comment by MohamadHosseinMohammadi** [comment]
<div dir="rtl" align=right>استفاده از برنامه‌ی proxychains
-proxychains چیست؟

proxychains ابزاری است که به شما اجازه میدهد برنامه‌ها را از طریق پروکسی HTTP یا SOCKS اجرا کنید. به عنوان مثال برنامه‌ی aria2 که یک نرم‌افزار مدیریت دانلود است از پروکسی نوع SOCKS پشتیبانی نمی‌کند. با استفاده از proxychains قادر هستید برنامه‌های مختلف را تحت پروکسی اجرا نمایید. proxychains بطور کلی قابلیت استفاده از پروکسی‌های زیر را دارد:
http, socks4, socks5

## -نصب proxychains
جهت نصب توسط مدیر بسته‌ی apt کافی است دستور زیر را در ترمینال وارد نمایید:
sudo apt-get install proxychains

## -تنظیمات proxychains
جهت استفاده از proxychains باید مشخصات آی‌پی و پورت پروکسی موردنظر را در فایل تنظیمات وارد کرد. برای ویرایش تنظبمات این برنامه دستور زیر را در ترمینال وارد کنید:
sudo nano /etc/proxychains.conf
(می‌توانید از ویرایشگر متن دیگری مثلاً از gedit به جای nano استفاده کنید.)
پس از اجرای این دستور فایل تنظیمات در ویرایشگر باز میشود. در این فایل توضیحاتی در مورد ساختار فایل تنظیمات مشاهده میکنید. در قسمت آخر فایل یعنی در بخش [ProxyList] خطوط زیر دیده میشود:
add proxy here ...
meanwile
defaults set to "tor"
socks4  127.0.0.1 9050
همانطور که مشاهده میکنید برنامه بصورت پیشفرض برای استفاده از آی‌پی و پورت برنامه‌ی پروکسی tor تنظیم گردیده است. درصورت لزوم میتوانید آی‌پی و پورت دیگری در خط جدید اضافه نمایید (مثلاً: http 127.0.0.1 8080) و سایر آی‌پی و پورت‌ها را حذف یا کامنت کنید. (درصورتی که کاراکتر # در ابتدای هر خط قرار گیرد، خط مذکور توضیح (comment) تلقی میگردد).

## -اجرای  proxychains
برای اجرای یک نرم‌افزار با استفاده از proxychains دستور زیر را در ترمینال وارد کنید:
proxychains <name_of_application>
مثلاً:
proxychains firefox  </div>

**Comment by jadijadi** [comment]
کلا ایده ام به سمت اینه که کمتر مسائل فنی اضافه کنیم و مسائل غیرفنی رو اضافه کنم (:
